Trainer:
  device: &device cuda
  batch_size: 1
  save_freq : 512

  lr: 1.e-4
  weight_decay: 1.e-4

  niter_schedule:
    opt_niter: [1, 2, 3, 4]
    opt_steps: [8192, 16384, 32768]


System:
  args:
    numPoints: 800
    match_cov_default: 0.25
    edge_width: 16

    optim:
      vectorize: true
      device: *device

  obscov:
    type: LearningCovariance
    args:
      eval_mode: false
      match_cov_default: 0.25
      min_flow_cov: 0.25
      modifier:
        type: ResidualCNNModifier
        args:
          device: *device
          patch_size: 15
  
  keypoint:
    type: CovAwareSelector
    args:
      device: *device
      kernel_size: 7
      mask_width: 32
      max_depth: auto
      max_depth_cov: 250.0
      max_match_cov: 100.0
  
  frontend:
    type: TRT_FlowFormerCovFrontend
    args:
      device: *device
      eval_mode: true
      weight: ./Model/MACVO_FrontendCov.pth
      dtype: fp32
      max_flow: -1
      enforce_positive_disparity: false
  
  optimizer:
    type: PyPoseTwoFramePGO
    args:
      device: *device
      vectorize: true
      parallel: false


Train:
  data: !flatten_seq 
    - !include ../../Sequence/Training_Dataset/TartanAir_Train.yaml
  preprocess:
    - type: SmartResizeFrame
      args: 
        height: 480
        width : 640
        interp: nearest

Evaluate:
  data: !flatten_seq 
    - !include ../../Sequence/Training_Dataset/TartanAirV2_Demo.yaml
