type: UniMatchMatcher
args:
  weight: ./Model/UniMatch/gmflow-scale2-regrefine6-mixdata.pth
  device: cuda
  task: flow
  num_refine: 6

  num_scales: 2
  feature_channels: 128
  upsample_factor: 4
  num_head: 1
  ffn_dim_expansion: 4
  num_transformer_layer: 6
  attn_type: swin

  attn_splits_list: [2, 8]
  corr_radius_list: [-1, 4]
  prop_radius_list: [-1, 1]
