type: Zed
name: straight_line_dyna
args:
  root: "/data2/datasets/yuhengq/zed_data/traverses/straight_line_dyna"

  # Camera Intrinsics
  fx: 735.9240
  fy: 735.7140
  cx: 964.8520
  cy: 622.2050
  bl: 0.119981

  width: 1920
  height: 1200
